%% Import data from spreadsheet
% Script for importing data from the following spreadsheet:
%
%    Workbook: C:\Users\Amir\MATLAB\Shift_Analysis\Gene_Shift_Analysis\Loregic.xlsx
%    Worksheet: All
%
% To extend the code for use with different selected data or a different spreadsheet, generate a function instead of a script.

% Auto-generated by MATLAB on 2018/11/13 13:38:45

%% Import the data
[~, ~, raw] = xlsread('C:\Users\Amir\MATLAB\Shift_Analysis\Gene_Shift_Analysis\Loregic.xlsx','All');
raw(cellfun(@(x) ~isempty(x) && isnumeric(x) && isnan(x),raw)) = {''};
cellVectors = raw(:,[1,2,3,4]);
raw = raw(:,5);

%% Replace non-numeric cells with NaN
R = cellfun(@(x) ~isnumeric(x) && ~islogical(x),raw); % Find non-numeric cells
raw(R) = {NaN}; % Replace non-numeric cells

%% Create output variable
data = reshape([raw{:}],size(raw));

%% Allocate imported array to column variable names
TF1 = cellVectors(:,1);
TF2 = cellVectors(:,2);
target = cellVectors(:,3);
logic_gate = cellVectors(:,4);
for i=2:length(data)
    score{i,1}=data(i);
    
end
Loregic_Tri = [TF1,TF2,target,logic_gate,score];

%% Clear temporary variables
clearvars data raw cellVectors R;